name: build-deploy-app.yml
run-name: ${{ github.actor }} has pushed to main and is deploying the app to Docker

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v4
        with:
          name: node-build
          path: dist/
      - run: npm test

  deploy_to_docker:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: node-build
          path: ./dist
      # Build Docker image using local dist
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cosh_scraper:backend --build-arg DIST_PATH=dist .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cosh_scraper:backend

      - name: Save Docker image to tarball
        run: docker save ${{ secrets.DOCKERHUB_USERNAME }}/cosh_scraper:backend -o cosh_scraper_backend.tar

      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: cosh_scraper_backend.tar
