name: build-deploy-app.yml
run-name: ${{ github.actor }} has pushed to main and is deploying the app to Docker

on:
  push:
#    branches:
#      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install -g pnpm # Keep pnpm install if you use it for other scripts (e.g., test)
      - run: npm ci # This uses package-lock.json for clean install
      - run: pnpm i # Keep pnpm i if you use it for other scripts
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v4
        with:
          name: node-build-dist
          path: dist/
      - run: pnpm test

  deploy_to_docker:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: node-build-dist
          path: ./dist

      - name: List contents of dist directory
        run: ls -lR ./dist # Keep this for now to confirm dist content

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/cosh_scraper:backend . # <--- ADDED --no-cache
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cosh_scraper:backend

      - name: Save Docker image to tarball
        run: docker save ${{ secrets.DOCKERHUB_USERNAME }}/cosh_scraper:backend -o cosh_scraper_backend.tar

      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: cosh_scraper_backend.tar
