name: build and test app
run-name: ${{ github.actor }} has opened a pull request and is building and testing the app

on:
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
